#!/bin/bash
# // font
# =========================================
# Quick Setup | Script Setup Manager
# Edition : Stable Edition V1.0
# Auther  : NevermoreSSH
# (C) Copyright 2022
# =========================================
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
IP=$(curl -s ipv4.icanhazip.com)
HOST="$(cat /etc/xray/domain)"
DATEVPS=$(date +"%d-%B-%Y")
ISPVPS=$(cat /etc/xray/isp)
TIME=10
CITY=$(cat /etc/xray/city)
GREEN="\e[92;1m"
BLUE="\033[36m"
RED='\033[0;31m'
NC='\033[0m'
#bottoket
source /etc/adminbot/var.txt
URL=https://api.telegram.org/bot$BOT_TOKEN/sendDocument
HOST="$(cat /etc/xray/domain)"
function BACKUPVPS() {
    mkdir -p /root/backup
    cp -r /usr/local/etc/xray/ /root/backup/xray/ >/dev/null 2>&1
	cp -r /etc/cron.d /root/backup/cron.d &> /dev/null
	cp -r /etc/crontab /root/backup/crontab &> /dev/null
	cp -r /etc/shadow /root/backup/shadow >/dev/null 2>&1
	cp -r /etc/gshadow /root/backup/gshadow >/dev/null 2>&1
	cp -r /etc/passwd /root/backup/passwd >/dev/null 2>&1
	cp -r /etc/group /root/backup/group >/dev/null 2>&1
    zip -r ${DATEVPS}.zip backup >/dev/null 2>&1
    
cd /root
curl -F chat_id="$ADMIN" -F document=@"${DATEVPS}.zip" -F caption="$HOST " $URL >/dev/null 2>&1

rm -f $HOST-$IP-${DATEVPS}.zip
rm -rf backup
}
cd /root
system
